dist: xenial
os: linux
language: python

python:
  - 3.7
  - 3.8

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/downloads

install: pip install ".[dev]" codecov
script: make test && codecov

jobs:
  include:

  - stage: pypi
    install:
      - pip install twine
    script:
      - python setup.py bdist_wheel
      - ls dist
      - twine upload dist/* -u ${PYPI_USER} -p ${PYPI_PASSWORD}
    if: tag IS present
