language: python

python:
  - 3.7
  - 3.8

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/downloads

install: pip install ".[dev]" codecov
script: make test && codecov

jobs:
  include:

  - stage: pypi
    services:
      - docker
    env: &pypi-env
      - CIBW_BUILD="cp37-* cp38-*"
    install: &pypi-install
      - pip install cibuildwheel twine
    script: &pypi-script
      - cibuildwheel --output-dir dist
      - if [ "$TRAVIS_OS_NAME" = "linux" ]; then python setup.py sdist ; fi
      - ls dist
      - twine upload dist/* -u ${PYPI_USER} -p ${PYPI_PASSWORD}
    if: tag IS present

  - stage: pypi
    os: osx
    language: generic
    env: *pypi-env
    install: *pypi-install
    script: *pypi-script
    if: tag IS present

  - stage: pypi
    os: windows
    language: shell
    env:
      - CIBW_BUILD="cp37-* cp38-*"
      - CIBW_BEFORE_BUILD="pip install cython"
      - PATH=/c/Python36:/c/Python36/Scripts:$PATH
    before_install:
      - choco install python3 --version 3.6.8 --no-progress -y
    install: *pypi-install
    script: *pypi-script
    if: tag IS present
